// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhnssQHR8bHy967zfWXZ_VRh1vjzWFjw',
    appId: '1:755728167237:web:5e639ca97d5ca1a41e0e2c',
    messagingSenderId: '755728167237',
    projectId: 'problem-spark',
    authDomain: 'problem-spark.firebaseapp.com',
    storageBucket: 'problem-spark.firebasestorage.app',
    measurementId: 'G-D4KGP4ZWSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66GP_4demYrbGGPvKagYAs9LrvqKeUvE',
    appId: '1:755728167237:android:d7e48163a7fa16611e0e2c',
    messagingSenderId: '755728167237',
    projectId: 'problem-spark',
    storageBucket: 'problem-spark.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfC7ExgfjL5PHVNFN4CK8QE_zolKaE8OY',
    appId: '1:755728167237:ios:ec510a34039c13b21e0e2c',
    messagingSenderId: '755728167237',
    projectId: 'problem-spark',
    storageBucket: 'problem-spark.firebasestorage.app',
    iosBundleId: 'com.example.problemSpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfC7ExgfjL5PHVNFN4CK8QE_zolKaE8OY',
    appId: '1:755728167237:ios:ec510a34039c13b21e0e2c',
    messagingSenderId: '755728167237',
    projectId: 'problem-spark',
    storageBucket: 'problem-spark.firebasestorage.app',
    iosBundleId: 'com.example.problemSpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGhnssQHR8bHy967zfWXZ_VRh1vjzWFjw',
    appId: '1:755728167237:web:00bb7b9628d2d4f21e0e2c',
    messagingSenderId: '755728167237',
    projectId: 'problem-spark',
    authDomain: 'problem-spark.firebaseapp.com',
    storageBucket: 'problem-spark.firebasestorage.app',
    measurementId: 'G-PHV2F1FEVH',
  );
}
